export const countries = {
  ES: "España",
  DE: "Alemania",
  FR: "Francia",
  IT: "Italia",
  AT: "Austria",
  BE: "Belgica",
  BG: "Bulgaria",
  AD: "Andorra",
  LT: "Lituania",
  EE: "Estonia",
  FI: "Finlandia",
  SM: "San Marino",
  SK: "Eslovaquia",
  SI: "Eslovenia",
  DK: "Dinamarca",
  SE: "Suecia",
  PT: "Portugal",
  VA: "Ciudad del Vaticano",
  LU: "Luxemburgo",
  CY: "Chipre",
  MT: "Malta",
};
